/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Components;

import GUI.Admin_Subject;
import GUI.Main_GUI;
import GUI.SV_Main_GUI;
import com.sun.java.accessibility.util.AWTEventMonitor;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author THANH PHU
 */
public class MenuCustom extends javax.swing.JPanel {

    /**
     * Creates new form MenuCustom
     */
    private final String[] GV={"Home","Exam","Question Bank"};
    private final String[] SV={"Home","Class"};
    private final String[] AD={"Subject","Class","Account"};
    public MenuCustom() {
        initComponents();
        setOpaque(false);
        repaint();
        revalidate();
    }
    private String role;
    public  MenuCustom(String role){
        
        initComponents();
        
        this.role=role;
        if(role.equalsIgnoreCase("GV"))
            initMenu(GV);
        else if(role.equalsIgnoreCase("SV"))
            initMenu(SV);
        else if(role.equalsIgnoreCase("AD"))
            initMenu(AD);
        setOpaque(false);
        repaint();
        revalidate();
    }
    public void initMenu(String[] items){
        List<MenuItemCustom> listItems= new ArrayList<>();
        for(String item:items){
            MenuItemCustom menuItem= new MenuItemCustom(item, "icons8-"+item.toLowerCase()+"-30");
            listItems.add(menuItem);
            menuItem.addActionListener(x->handleClick(menuItem));
        }
//         if(role.equalsIgnoreCase("GV")){
//             
//         }
//        else if(role.equalsIgnoreCase("SV")){
//             SV_Main_GUI gui= new SV_Main_GUI();
//             Main_GUI.main_panel.removeAll();
//             Main_GUI.main_panel.add(gui);
//        }
//        else if(role.equalsIgnoreCase("AD")){
//             Admin_Subject gui= new Admin_Subject();
//             Main_GUI.main_panel.removeAll();
//             Main_GUI.main_panel.add(gui);
//        }
        menuItemList1.updateMenu(listItems);
    }
    public void handleClick(MenuItemCustom item){
        Avatar.updateTitle(item.getItemText());
        System.out.println(item.getItemText());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        menuItemList1 = new Components.MenuItemList();
        button1 = new Components.Button();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/favicon_70.png"))); // NOI18N

        button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-logout-64.png"))); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menuItemList1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menuItemList1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
            
    }//GEN-LAST:event_button1ActionPerformed
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        // Vẽ nền bo tròn
        g2.setColor(getBackground());
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 30, 30);

        g2.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Components.Button button1;
    private javax.swing.JLabel jLabel1;
    private Components.MenuItemList menuItemList1;
    // End of variables declaration//GEN-END:variables
}
