/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Components;

import DB.CreateDB;
import Dao.MonHoc_DAO;
import Entity.BaiKiemTra;
import GUI.Main_GUI;
import jakarta.persistence.EntityManager;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author THANH PHU
 */
public class Subject extends javax.swing.JPanel {

    /**
     * Creates new form Subject
     */
    public Subject() {
        initComponents();
    }
     private static DateTimeFormatter dateDF= DateTimeFormatter.ofPattern("dd/MM/yyyy");
     private static DateTimeFormatter timeDF= DateTimeFormatter.ofPattern("HH:mm");

    public RoundedGradientPanel getRoundedGradientPanel1() {
        return roundedGradientPanel1;
    }

    public void setRoundedGradientPanel1(RoundedGradientPanel roundedGradientPanel1) {
        this.roundedGradientPanel1 = roundedGradientPanel1;
    }
     
    
    public Subject(BaiKiemTra bkt ){
        EntityManager em= CreateDB.createDB();
        MonHoc_DAO mh_dao= new MonHoc_DAO(em);
        initComponents();
        subject.setText(mh_dao.getTenMonHocTheoBaiKiemTra(bkt.getMaBaiKiemTra()));
        time.setText(bkt.getThoiGianLamBai()+" phút");
        date.setText(timeDF.format(bkt.getThoiGianBatDau())+" "+dateDF.format(bkt.getThoiGianBatDau()));
    }
             
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedGradientPanel1 = new Components.RoundedGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        subject = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        button1 = new Components.Button();

        setOpaque(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/subject.png"))); // NOI18N

        subject.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        subject.setForeground(new java.awt.Color(255, 255, 255));
        subject.setText("Java Phan Tan");
        subject.setPreferredSize(new java.awt.Dimension(240, 25));

        time.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        time.setForeground(new java.awt.Color(255, 255, 255));
        time.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-time-18.png"))); // NOI18N
        time.setText("30 minutes");

        date.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        date.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-calender-18.png"))); // NOI18N
        date.setText("15:30 25/03/2025");

        button1.setBackground(new java.awt.Color(26, 26, 25));
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-play-18.png"))); // NOI18N
        button1.setText("Tham Gia");
        button1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout roundedGradientPanel1Layout = new javax.swing.GroupLayout(roundedGradientPanel1);
        roundedGradientPanel1.setLayout(roundedGradientPanel1Layout);
        roundedGradientPanel1Layout.setHorizontalGroup(
            roundedGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundedGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundedGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subject, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(roundedGradientPanel1Layout.createSequentialGroup()
                        .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        roundedGradientPanel1Layout.setVerticalGroup(
            roundedGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundedGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundedGradientPanel1Layout.createSequentialGroup()
                        .addGroup(roundedGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(roundedGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(time)
                            .addComponent(date))
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addGroup(roundedGradientPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(roundedGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundedGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Components.Button button1;
    private javax.swing.JLabel date;
    private javax.swing.JLabel jLabel1;
    private Components.RoundedGradientPanel roundedGradientPanel1;
    private javax.swing.JLabel subject;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
