/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author Admin
 */
public class DanhSachLopGVGUI extends javax.swing.JPanel {

    /**
     * Creates new form DanhSachLopGVGUI
     */
    public DanhSachLopGVGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        myTextField1 = new Components.MyTextField();
        button1 = new Components.Button();
        jLabel2 = new javax.swing.JLabel();
        comboBoxSuggestion1 = new Components.ComboBoxSuggestion();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        groupCard2 = new Components.GroupCard();
        groupCard1 = new Components.GroupCard();
        groupCard3 = new Components.GroupCard();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);

        myTextField1.setText("myTextField1");
        jPanel1.add(myTextField1);

        button1.setText("button1");
        jPanel1.add(button1);

        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jPanel1.add(comboBoxSuggestion1);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel3.setLayout(new java.awt.GridLayout(0, 1));
        jPanel3.add(groupCard2);
        jPanel3.add(groupCard1);
        jPanel3.add(groupCard3);

        jScrollPane1.setViewportView(jPanel3);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Components.Button button1;
    private Components.ComboBoxSuggestion comboBoxSuggestion1;
    private Components.GroupCard groupCard1;
    private Components.GroupCard groupCard2;
    private Components.GroupCard groupCard3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private Components.MyTextField myTextField1;
    // End of variables declaration//GEN-END:variables
}
