/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Components.EventPagination;
import Components.Model_Card;
import Components.PaginationItemRenderStyle1;
import Dao.BaiKiemTra_DAO;
import Dao.DeThi_DAO;
import Dao.LopHoc_DAO;
import Dao.MonHoc_DAO;
import Entity.BaiKiemTra;
import Entity.DeThi;
import Entity.LopHoc;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.ImageIcon;

/**
 *
 * @author THANH PHU
 */
public class GV_Classroom extends javax.swing.JPanel {

    private DeThi_DAO dt_dao= new DeThi_DAO(Main_GUI.em);
    private LopHoc_DAO lh_dao= new LopHoc_DAO(Main_GUI.em);
    private BaiKiemTra_DAO bkt_dao= new BaiKiemTra_DAO(Main_GUI.em);
    private MonHoc_DAO mh_dao= new MonHoc_DAO(Main_GUI.em);
    private ArrayList<LopHoc> dsLopHocs;
    private List<BaiKiemTra> dsBKT; 
    
    public GV_Classroom() {
        //fix
        dsLopHocs= lh_dao.getDanhSachLopHocTheoGV(Main_GUI.tk.getMaTaiKhoan());
        dsBKT= bkt_dao.getBaiKiemTraTheoTaiKhoanGV(Main_GUI.tk.getMaTaiKhoan());
        
        initComponents();
        pagination1.setPaginationItemRender(new PaginationItemRenderStyle1());
        initComboBox();
        loadData(1);
        pagination1.addEventPagination(new EventPagination(){
            @Override
            public void pageChanged(int page) {
                loadData(page);
            }
            
        });
        searchTextField1.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                search();
            }
        });
    }
    public void search(){
        String search= searchTextField1.getText();
        Object monHocObj = comboBoxSuggestion2.getSelectedItem();
        Object namHocObj = comboBoxSuggestion1.getSelectedItem();

        String monHoc = (comboBoxSuggestion2.getSelectedIndex() == 0 || monHocObj == null) ? "" : monHocObj.toString();
        String namHoc = (comboBoxSuggestion1.getSelectedIndex() == 0 || namHocObj == null) ? "" : namHocObj.toString();
        dsLopHocs= lh_dao.filterLopHocCuaGiaoVien(search, search,
                monHoc, 
                namHoc,
                Main_GUI.tk.getMaTaiKhoan());
         loadData(1);
    }
    public void reloadData(){
        //fix
        initComboBox();
        dsLopHocs= lh_dao.getDanhSachLopHocTheoGV(Main_GUI.tk.getMaTaiKhoan());
        loadData(1);
    }
    public void loadData(int page){
        
        int limit= 9;
        int totalPage=(int) Math.ceil((double)dsLopHocs.size()/limit);
        pagination1.setPagegination(page, totalPage);
        int currentPage = page; // Bạn có thể thay đổi thành biến động nếu muốn điều khiển trang
        int skip = (currentPage - 1) * limit;
        ArrayList<LopHoc> lopHocsToShow = dsLopHocs.stream()
        .skip(skip)
        .limit(limit)
        .collect(Collectors.toCollection(ArrayList::new));
        
        
        listLopHoc1.updateList(lopHocsToShow);
    }
    public void initComboBox(){
        comboBoxSuggestion1.removeAllItems();
        comboBoxSuggestion2.removeAllItems();
        comboBoxSuggestion1.addItem("Năm học");
        
        lh_dao.getDSNamHocGV(Main_GUI.tk.getMaTaiKhoan()).forEach(x->{
            comboBoxSuggestion1.addItem(x);
        });
        comboBoxSuggestion2.addItem("Môn học");
        
        //fix
        mh_dao.getDanhSachMonHocCuaGiaoVien(Main_GUI.tk.getMaTaiKhoan()).forEach(x->{
            comboBoxSuggestion2.addItem(x.getTenMonHoc());
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel1 = new Components.RoundedPanel();
        circleBackgroundPanel1 = new Components.CircleBackgroundPanel();
        searchTextField1 = new Components.SearchTextField();
        button2 = new Components.Button();
        comboBoxSuggestion1 = new Components.ComboBoxSuggestion();
        comboBoxSuggestion2 = new Components.ComboBoxSuggestion();
        roundedPanel2 = new Components.RoundedPanel();
        listLopHoc1 = new Components.ListLopHoc(dsLopHocs);
        jPanel1 = new javax.swing.JPanel();
        pagination1 = new Components.Pagination();

        setOpaque(false);

        roundedPanel1.setBackground(new java.awt.Color(245, 245, 245));

        circleBackgroundPanel1.setColor1(new java.awt.Color(58, 138, 125));

        button2.setBorder(null);
        button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-reload-30.png"))); // NOI18N
        button2.setText("Làm mới");
        button2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        button2.setPreferredSize(new java.awt.Dimension(82, 36));
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        comboBoxSuggestion1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Năm học" }));
        comboBoxSuggestion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxSuggestion1ActionPerformed(evt);
            }
        });

        comboBoxSuggestion2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Môn học" }));
        comboBoxSuggestion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxSuggestion2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout circleBackgroundPanel1Layout = new javax.swing.GroupLayout(circleBackgroundPanel1);
        circleBackgroundPanel1.setLayout(circleBackgroundPanel1Layout);
        circleBackgroundPanel1Layout.setHorizontalGroup(
            circleBackgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(circleBackgroundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comboBoxSuggestion1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(comboBoxSuggestion2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        circleBackgroundPanel1Layout.setVerticalGroup(
            circleBackgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, circleBackgroundPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(circleBackgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxSuggestion1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxSuggestion2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        roundedPanel2.setBackground(new java.awt.Color(255, 255, 255));

        listLopHoc1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(pagination1);

        javax.swing.GroupLayout roundedPanel2Layout = new javax.swing.GroupLayout(roundedPanel2);
        roundedPanel2.setLayout(roundedPanel2Layout);
        roundedPanel2Layout.setHorizontalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listLopHoc1, javax.swing.GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        roundedPanel2Layout.setVerticalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(listLopHoc1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(circleBackgroundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(roundedPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addComponent(circleBackgroundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roundedPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        reloadData();
    }//GEN-LAST:event_button2ActionPerformed

    private void comboBoxSuggestion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxSuggestion1ActionPerformed
        search();
    }//GEN-LAST:event_comboBoxSuggestion1ActionPerformed

    private void comboBoxSuggestion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxSuggestion2ActionPerformed
        search();
    }//GEN-LAST:event_comboBoxSuggestion2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Components.Button button2;
    private Components.CircleBackgroundPanel circleBackgroundPanel1;
    private Components.ComboBoxSuggestion comboBoxSuggestion1;
    private Components.ComboBoxSuggestion comboBoxSuggestion2;
    private javax.swing.JPanel jPanel1;
    private Components.ListLopHoc listLopHoc1;
    private Components.Pagination pagination1;
    private Components.RoundedPanel roundedPanel1;
    private Components.RoundedPanel roundedPanel2;
    private Components.SearchTextField searchTextField1;
    // End of variables declaration//GEN-END:variables
}
