/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import Components.Avatar;
import Components.Model_Card;
import Dao.ITaiKhoan_DAO;
import Dao.TaiKhoan_DAO;
import Entity.TaiKhoan;
import jakarta.persistence.EntityManager;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import service.RmiServiceLocator;

/**
 *
 * @author THANH PHU
 */
public class Main_GUI extends javax.swing.JFrame {


    public static TaiKhoan tk = new TaiKhoan();
    public static EntityManager em;
    private ITaiKhoan_DAO tk_dao= RmiServiceLocator.getTaiKhoanDao();
    public Main_GUI() throws RemoteException {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        ImageIcon img = new ImageIcon(getClass().getResource("/Image/favicon_1.png"));
        setIconImage(img.getImage());
        setTitle("SoloSmart - Multiple Choice App");
    }
    public Main_GUI(TaiKhoan tk) throws RemoteException {
        
        this.em= DangNhapGUI.em;
        this.tk= tk;
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        ImageIcon img = new ImageIcon(getClass().getResource("/Image/favicon_1.png"));
        setIconImage(img.getImage());
        setTitle("SoloSmart - Multiple Choice App");
        String vaiTro= tk.getVaiTro().equalsIgnoreCase("GV")? "Giảng viên":tk.getVaiTro().equalsIgnoreCase("SV")?"Sinh Viên":"Quản trị viên";
        avatar2.setData(new Model_Card(new ImageIcon(getClass().getResource("")),
                vaiTro, tk.getHo()+" "+tk.getTen()));
        if(tk.getGioiTinh().equalsIgnoreCase("nam")){
            avatar2.setAvt(true);
        }
        else{
            avatar2.setAvt(false);
        }
        if(tk.getVaiTro().equalsIgnoreCase("SV")){
            main_panel.add(new SV_Classroom());
        }
        else if(tk.getVaiTro().equalsIgnoreCase("GV")){
            main_panel.add(new GV_Classroom());
        }else{
            main_panel.add(new Admin_Subject());
            Avatar.updateTitle("Subject");
        }
        
        this.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent e) {
                try {
                    tk_dao.updateTrangThaiOnline(tk);
                } catch (RemoteException ex) {
                    Logger.getLogger(Main_GUI.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() throws RemoteException {

        menuCustom1 = new Components.MenuCustom(Main_GUI.tk.getVaiTro());
        avatar2 = new Components.Avatar();
        main_panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(61, 141, 122));
        setResizable(false);

        avatar2.setColor1(new java.awt.Color(0, 102, 102));
        avatar2.setColor2(new java.awt.Color(61, 141, 122));
        avatar2.setData(new Model_Card(new ImageIcon(getClass().getResource("")), "Giáo Viên",
            "Lâm Ngọc Thanh Phú"));

    main_panel.setBackground(new java.awt.Color(255, 255, 255));
    main_panel.setLayout(new java.awt.BorderLayout());

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(10, 10, 10)
            .addComponent(menuCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(avatar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(10, 10, 10)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(avatar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
                .addGroup(layout.createSequentialGroup()
                    .addComponent(menuCustom1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(5, 5, 5))))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Main_GUI().setVisible(true);
                } catch (RemoteException e) {
                    throw new RuntimeException(e);
                }
            }
        });
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Components.Avatar avatar2;
    public static javax.swing.JPanel main_panel;
    private Components.MenuCustom menuCustom1;
    // End of variables declaration//GEN-END:variables
}
