/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Dao.BaiKiemTra_DAO;
import Dao.CauHoi_DAO;
import Dao.DeThi_DAO;
import Dao.DsCauTraLoi_DAO;
import Dao.KetQuaHocTap_DAO;
import Dao.KetQuaKiemTra_DAO;
import Entity.*;
import java.time.Duration;
import java.time.LocalDateTime;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.*;

/**
 *
 * @author THANH PHU
 */
public class SV_KiemTra extends javax.swing.JFrame {

    /**
     * Creates new form SV_KiemTra
     */
    private BaiKiemTra_DAO bkt_dao=new BaiKiemTra_DAO(Main_GUI.em);
    private CauHoi_DAO chdao= new CauHoi_DAO(Main_GUI.em);
    private DeThi_DAO dt_dao= new DeThi_DAO(Main_GUI.em);
    private DsCauTraLoi_DAO dsCauTraLoi_DAO = new DsCauTraLoi_DAO(Main_GUI.em);
    private KetQuaKiemTra_DAO ketQuaKiemTra_DAO = new KetQuaKiemTra_DAO(Main_GUI.em);
    private KetQuaHocTap_DAO ketQuaHocTap_DAO = new KetQuaHocTap_DAO(Main_GUI.em);
    private BaiKiemTra baiKiemTra;
    private TaiKhoan tk;
    private LocalDateTime startTime;
    
    public SV_KiemTra() {
        initComponents();
    }
    public SV_KiemTra(BaiKiemTra bkt){
        this.baiKiemTra = bkt;
        this.tk = Main_GUI.tk;
        initComponents();
        ArrayList<CauHoi> dsCauHoi= chdao.getDsCauHoiTheoDeThi(bkt.getDeThi().getMaDeThi());
        listCauHoiKiemTra1.updateList(dsCauHoi);
        startTime = LocalDateTime.now(); // Ghi lại thời gian bắt đầu
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        listCauHoiKiemTra1 = new Components.ListCauHoiKiemTra();
        circleBackgroundPanel1 = new Components.CircleBackgroundPanel();
        button1 = new Components.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(listCauHoiKiemTra1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(listCauHoiKiemTra1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        circleBackgroundPanel1.setColor1(new java.awt.Color(58, 138, 125));

        button1.setText("nộp");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout circleBackgroundPanel1Layout = new javax.swing.GroupLayout(circleBackgroundPanel1);
        circleBackgroundPanel1.setLayout(circleBackgroundPanel1Layout);
        circleBackgroundPanel1Layout.setHorizontalGroup(
            circleBackgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(circleBackgroundPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        circleBackgroundPanel1Layout.setVerticalGroup(
            circleBackgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, circleBackgroundPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(circleBackgroundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(circleBackgroundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed

        LocalDateTime endTime = LocalDateTime.now(); // Thời gian kết thúc
        long durationInMinutes = Duration.between(startTime, endTime).toMinutes(); // Tính phút

        if (durationInMinutes == 0) {
            durationInMinutes = 1; // Tối thiểu ghi nhận là 1 phút nếu quá nhanh
        }
        // tạo kết quả kiểm tra
        String maKqkt = ketQuaKiemTra_DAO.generateMa();
        boolean diemCaoNhat = true;
        float diemSo = 0;
        int lanThu = 1;
        // tạm cho là 10p
        int thoiGianLamBai = (int) durationInMinutes;
        
        ketQuaKiemTra_DAO.themKetQuaKiemTra(new KetQuaKiemTra(maKqkt,diemSo,thoiGianLamBai,lanThu,diemCaoNhat,baiKiemTra,tk));
        
        //lấy ra danh sách câu trả lời
        List<String> dsCauTraLoi = listCauHoiKiemTra1.getDsLuaChonCuaSinhVien();
        //themCauTraLoi
        for(String cauTraLoi : dsCauTraLoi) {
            boolean kq = dsCauTraLoi_DAO.themCauTraLoi(maKqkt, cauTraLoi);
            System.out.println(kq);
        }
        //tinhDiemChoSinhVien
        float diem = ketQuaKiemTra_DAO.tinhDiemChoSinhVien(tk.getMaTaiKhoan(), baiKiemTra.getMaBaiKiemTra());
        //update điểm
        ketQuaKiemTra_DAO.updateKetQuaKiemTra(new KetQuaKiemTra(maKqkt,diem,thoiGianLamBai,lanThu,diemCaoNhat,baiKiemTra,tk));
        //updateDiemCaoNhatChoBaiKiemTraCuaSinhVien
        ketQuaKiemTra_DAO.updateDiemCaoNhatChoBaiKiemTraCuaSinhVien(tk.getMaTaiKhoan(), baiKiemTra.getMaBaiKiemTra());
        
        //cập nhật lại kết quả học tập của sinh viên
        Map<String, Float> map = ketQuaHocTap_DAO.getDiemHocTapCuaSinhVien(tk.getMaTaiKhoan(), baiKiemTra.getLopHoc().getMaLop());
        float diemThuongKy = map.get("0.2");
        float diemGiuaKy = map.get("0.3");
        float diemCuoiKy = map.get("0.5");
        float diemTBMon = (float) (diemThuongKy * 0.2 + diemGiuaKy * 0.3 + diemCuoiKy * 0.5);
        KetQuaHocTap ketQuaHocTapNew = new KetQuaHocTap(diemThuongKy,diemGiuaKy,diemCuoiKy,diemTBMon,tk,new LopHoc(baiKiemTra.getLopHoc().getMaLop()));
        ketQuaHocTap_DAO.capNhatKetQuaHocTap(ketQuaHocTapNew);
        dispose();
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SV_KiemTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SV_KiemTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SV_KiemTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SV_KiemTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SV_KiemTra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Components.Button button1;
    private Components.CircleBackgroundPanel circleBackgroundPanel1;
    private javax.swing.JPanel jPanel1;
    private Components.ListCauHoiKiemTra listCauHoiKiemTra1;
    // End of variables declaration//GEN-END:variables
}
